export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  BERTH_NOT_FOUND: "BERTH_NOT_FOUND",
  VESSEL_NOT_FOUND: "VESSEL_NOT_FOUND",
  SLOT_NOT_FOUND: "SLOT_NOT_FOUND",
  BERTH_LENGTH_EXCEEDED: "BERTH_LENGTH_EXCEEDED",
  BERTH_DRAFT_EXCEEDED: "BERTH_DRAFT_EXCEEDED",
  SLOT_NOT_EMPTY: "SLOT_NOT_EMPTY",
  PLAN_ALREADY_PROCESSED: "PLAN_ALREADY_PROCESSED",
  SLOT_REQUIRED: "SLOT_REQUIRED",
  INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
  CONCURRENT_UPDATE: "CONCURRENT_UPDATE"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
