export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  VESSEL_NOT_FOUND: "VESSEL_NOT_FOUND",
  BERTH_NOT_FOUND: "BERTH_NOT_FOUND",
  SLOT_NOT_FOUND: "SLOT_NOT_FOUND",
  INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
  VESSEL_BERTH_MISMATCH: "VESSEL_BERTH_MISMATCH",
  SLOT_NOT_EMPTY: "SLOT_NOT_EMPTY",
  PLAN_ALREADY_PROCESSED: "PLAN_ALREADY_PROCESSED"
} as const;
